# WHAT IS THIS FOR?
# This is a copy of Dockerfile, but prior to compiling, will set difficult to 500, resets all the
# seed nodes to 127.0.0.1 (to avoid annoying mainnet), changes the daemon name to "TortleCoin, and mixes up the network ID.
# Useless for mainnet, but used to setup a testnet with checkpoints, and not have to spend days mining to get to the next block!
#
# daemon runs in the background
# run something like tail /var/log/Conceald/current to see the status
# be sure to run with volumes, ie:
# docker run -v $(pwd)/Conceald:/var/lib/Conceald -v $(pwd)/wallet:/home/Conceal --rm -ti Conceal:0.2.2
ARG base_image_version=0.10.0
FROM phusion/baseimage:$base_image_version

ADD https://github.com/just-containers/s6-overlay/releases/download/v1.21.2.2/s6-overlay-amd64.tar.gz /tmp/
RUN tar xzf /tmp/s6-overlay-amd64.tar.gz -C /

ADD https://github.com/just-containers/socklog-overlay/releases/download/v2.1.0-0/socklog-overlay-amd64.tar.gz /tmp/
RUN tar xzf /tmp/socklog-overlay-amd64.tar.gz -C /

# Get the latest checkpoints (we don't care about being _100%_ up-to-date, but we need to be past block 350K for the algo change to CN_lite_v1)
ADD https://raw.githubusercontent.com/Conceal/checkpoints/master/checkpoints.csv /tmp/

# In a multi-node testnet, we'll want to have the slave nodes "wait" for the master node to wake up, so let's get ready
ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh /tmp/

ARG Conceal_VERSION=v0.4.3
ENV Conceal_VERSION=${Conceal_VERSION}

# install build dependencies
# checkout the latest tag
# build and install
RUN apt-get update && \
    apt-get install -y \
      build-essential \
      python-dev \
      gcc-4.9 \
      g++-4.9 \
      git cmake \
      libboost1.58-all-dev \
      librocksdb-dev && \
    git clone https://github.com/TheCircleFoundation/Conceal/Conceal.git /src/Conceal && \
    cd /src/Conceal && \
    git checkout $Conceal_VERSION && \
    sed -i '/std::vector<uint64_t> timestamps_o(timestamps);/i \\/*\n   Lower difficulty to static 500 for testnet\n   The rest of this function is ignored\n*\/\nreturn 500;\n\n' src/CryptoNoteCore/Currency.cpp && \
    sed -i -e 's/"104.236.227.176:11897",/"172.16.76.11:11897",/g' src/CryptoNoteConfig.h && \
    sed -i -e 's/"46.101.132.184:11897",/"172.16.76.12:11897",/g' src/CryptoNoteConfig.h && \
    sed -i -e 's/"163.172.147.52:11897",/"172.16.76.13:11897",/g' src/CryptoNoteConfig.h && \
    sed -i -e 's/"51.15.138.214:11897",/"192.168.76.11:11897",/g' src/CryptoNoteConfig.h && \
    sed -i -e 's/"51.15.137.77:11897",/"192.168.76.12:11897",/g' src/CryptoNoteConfig.h && \
    sed -i -e 's/"174.138.68.141:11897", \/\/\^ rock/"192.168.76.13:11897",/g' src/CryptoNoteConfig.h && \
    sed -i -e 's/"145.239.88.119:11999", \/\/cision/"10.0.76.11:11897",/g' src/CryptoNoteConfig.h && \
    sed -i -e 's/"142.44.242.106:11897", \/\/tom/"10.0.76.12:11897",/g' src/CryptoNoteConfig.h && \
    sed -i -e 's/"165.227.252.132:11897" \/\/iburnmycd/"10.0.76.13:11897",/g' src/CryptoNoteConfig.h && \
    sed -i -e 's/Conceal/TortleCoin/' src/CryptoNoteConfig.h && \
    sed -i -e 's/0xcf, 0x52, 0x57/0x52, 0xcf, 0x57/' src/P2p/P2pNetworks.h && \
    mkdir build && \
    cd build && \
    cmake -DCMAKE_CXX_FLAGS="-g0 -Os -fPIC -std=gnu++11" .. && \
    make -j$(nproc) && \
    mkdir -p /usr/local/bin && \
    cp src/Conceald /usr/local/bin/Conceald && \
    cp src/walletd /usr/local/bin/walletd && \
    cp src/simplewallet /usr/local/bin/simplewallet && \
    cp src/miner /usr/local/bin/miner && \
    strip /usr/local/bin/Conceald && \
    strip /usr/local/bin/walletd && \
    strip /usr/local/bin/simplewallet && \
    strip /usr/local/bin/miner && \
    cd / && \
    rm -rf /src/Conceal && \
    apt-get remove -y build-essential python-dev gcc-4.9 g++-4.9 git cmake libboost1.58-all-dev librocksdb-dev && \
    apt-get autoremove -y && \
    apt-get install -y  \
      libboost-system1.58.0 \
      libboost-filesystem1.58.0 \
      libboost-thread1.58.0 \
      libboost-date-time1.58.0 \
      libboost-chrono1.58.0 \
      libboost-regex1.58.0 \
      libboost-serialization1.58.0 \
      libboost-program-options1.58.0 \
      libicu55

# setup the Conceald service
RUN useradd -r -s /usr/sbin/nologin -m -d /var/lib/Conceald Conceald && \
    useradd -s /bin/bash -m -d /home/Conceal Conceal && \
    mkdir -p /etc/services.d/Conceald/log && \
    mkdir -p /var/log/Conceald && \
    echo "#!/usr/bin/execlineb" > /etc/services.d/Conceald/run && \
    echo "fdmove -c 2 1" >> /etc/services.d/Conceald/run && \
    echo "cd /var/lib/Conceald" >> /etc/services.d/Conceald/run && \
    echo "export HOME /var/lib/Conceald" >> /etc/services.d/Conceald/run && \
    echo "s6-setuidgid Conceald /usr/local/bin/Conceald --log-level=2" >> /etc/services.d/Conceald/run && \
    chmod +x /etc/services.d/Conceald/run && \
    chmod +x /tmp/wait-for-it.sh && \
    chown nobody:nogroup /var/log/Conceald && \
    echo "#!/usr/bin/execlineb" > /etc/services.d/Conceald/log/run && \
    echo "s6-setuidgid nobody" >> /etc/services.d/Conceald/log/run && \
    echo "s6-log -bp -- n20 s1000000 /var/log/Conceald" >> /etc/services.d/Conceald/log/run && \
    chmod +x /etc/services.d/Conceald/log/run && \
    echo "/var/lib/Conceald true Conceald 0644 0755" > /etc/fix-attrs.d/Conceald-home && \
    echo "/home/Conceal true Conceal 0644 0755" > /etc/fix-attrs.d/Conceal-home && \
    echo "/tmp/checkpoints.csv true Conceal 0644 0755" > /etc/fix-attrs.d/Conceal-checkpoints && \
    echo "/var/log/Conceald true nobody 0644 0755" > /etc/fix-attrs.d/Conceald-logs

VOLUME ["/var/lib/Conceald", "/home/Conceal","/var/log/Conceald"]

ENTRYPOINT ["/init"]
CMD ["/usr/bin/execlineb", "-P", "-c", "emptyenv cd /home/Conceal export HOME /home/Conceal s6-setuidgid Conceal tail -f /var/log/Conceald/current"]
