name: ARM

on:
  push:
    tags:
    - '*'

jobs:
  build-arm:
    name: ARM
    runs-on: [ARM]
    steps:
      - uses: actions/checkout@master

      - name: Build
        id: build
        run: |
          BOOST_ROOT=
          sudo apt-get purge '*boost*'
          sudo apt install -y libboost-all-dev
          build_folder="build/debug"
          ccx_ver=$(echo "$GITHUB_REF" | sed 's|refs/tags/||')
          ccx_ver_folder=$(echo $ccx_ver | sed 's/\.//g')
          release_name=ccx-cli-arm-v"$ccx_ver"
          mkdir -p "$build_folder"
          cd "$build_folder"
          cmake ../..
          make -j2
          mkdir -p "$release_name/$ccx_ver_folder"
          exeFiles=()
          for f in src/*; do [[ -x $f && -f $f ]] && exeFiles+=( "$f" ); done
          cp "${exeFiles[@]}" "$release_name/$ccx_ver_folder"
          cd "$release_name"
          tar -czf "$release_name".tar.gz "$ccx_ver_folder"
          sha256=$(shasum -a 256 "$release_name".tar.gz | awk '{print toupper($1)}')
          asset_path="./$build_folder/$release_name/$release_name.tar.gz"
          echo "::set-output name=sha256::${sha256}"
          echo "::set-output name=release_name::${release_name}.tar.gz"
          echo "::set-output name=asset_path::${asset_path}"
          echo "::set-output name=ccx_ver::${ccx_ver}"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.build.outputs.asset_path }}
          name: Conceal Core CLI v${{ steps.build.outputs.ccx_ver }}
          body: |
            **${{ steps.build.outputs.release_name }}**
            ${{ steps.build.outputs.sha256 }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
